### ISSUE TITLE
[FEATURE]: Add filter to rule

### ISSUE THREAD

**Issue by pierre-monnet** [databrickslabs/dqx#140]
### Is there an existing issue for this?

- [x] I have searched the existing issues

#### Problem
I need to apply rules to a part of a DataFrame.

#### Context
We have a table of tracking events, and depending on the type of event, we want to apply a rule or not.

#### Example
```
+---+------------+-----------+---------+--------+
| id|  event_type|button_name|page_from|page_url|
+---+------------+-----------+---------+--------+
|  1|   page_view|       NULL|     NULL|   /home|
|  2|button_click|      login|    /home|    NULL|
|  3|   page_view|       NULL|     NULL|  /login|
|  4|button_click|    sign_in|   /login|    NULL|
+---+------------+-----------+---------+--------+
```
##### In this case
- if the `event_type` is "page_view", then `page_url` must be non-null
- if the `event_type` is "button_click", then `button_name` and `page_from` must be non-null.

#### Purpose
For this simple example, a `sql_expression` with both conditions could solve the problem, but for readability, I find it more elegant to keep native rules (here `is_not_null`) to which we apply a filter. This is even more the case when we want to apply a rule to a list of columns, it's much more readable to do that.

### Proposed Solution

```
- criticality: "error"
  filter: "event_type='page_view'"
  check:
    function: "is_not_null"
    arguments:
      col_name: "page_url"
- criticality: "error"
  filter: "event_type='button_click'"
  check:
    function: "is_not_null"
    arguments:
      col_names: 
        - "button_name"
        - "page_from"
```

### Additional Context

I started a draft PR (#141) with a simple working purpose but there are still a lot of things to validate, for example, how to display filter in `_error` or `_warning` result.
