### ISSUE TITLE
is_not_null_and_not_empty and is_not_empty Checks Fail in DQX v0.1.10 (TypeError: 'Column' object is not callable)

### ISSUE THREAD

**Issue by HoussemUp** [databrickslabs/dqx#158]
### Current Behavior

In Databricks Labs DQX v0.1.10, the is_not_null_and_not_empty and is_not_empty functions fail with the following error:
`TypeError: 'Column' object is not callable
This check used to work correctly in earlier versions.

`

### Expected Behavior

The validation should run successfully without error.

### Steps To Reproduce

1. Use the following YAML validation rule:
```
- criticality: error
  check:
    function: is_not_null_and_not_empty
    arguments:
      col_name: column1
```

2. Run apply_checks_by_metadata() with a sample DataFrame.
3. The error occurs inside col_functions.py, specifically: 
`condition = column.isNull() | (column.try_cast("string") == F.lit(""))`

### Cloud

AZURE

### Operating System

Windows
